### ISSUE TITLE
Prompts for the two models

### ISSUE THREAD

**Issue by skpig** [saschaschramm/chatgpt#1]
Hey, thanks for sharing the results. Could you please provide the prompts?

**Comment by saschaschramm** [comment]
Thanks for your question.

For the gpt-4 run the prompt (user message) was 
Complete the following code:\n{code}

For the other models the prompt was slightly different. For the pretrained-only models (e.g. code-davinci-002) I didn’t use the instruction „Complete the following prompt:\n“

**Comment by skpig** [comment]
Thank you!

**Comment by lxy444** [comment]
> Thanks for your question.
> 
> For the gpt-4 run the prompt (user message) was Complete the following code:\n{code}
> 
> For the other models the prompt was slightly different. For the pretrained-only models (e.g. code-davinci-002) I didn’t use the instruction „Complete the following prompt:\n“

Thanks! Could you please your prompt for gpt-3.5-turbo?

**Comment by saschaschramm** [comment]
> > Thanks for your question.
> > For the gpt-4 run the prompt (user message) was Complete the following code:\n{code}
> > For the other models the prompt was slightly different. For the pretrained-only models (e.g. code-davinci-002) I didn’t use the instruction „Complete the following prompt:\n“
> 
> Thanks! Could you please your prompt for gpt-3.5-turbo?

I've updated the README.

Prompt:
Complete the following code. Use ```python to put the Python code in markdown quotes:\n{code}
