### ISSUE TITLE
gpt-4 token

### ISSUE THREAD

**Issue by liudongmiao** [saschaschramm/chatgpt#2]
> It's unclear why the model returns 11 prompt tokens instead of 12. Maybe there is no \n after the role user.

See https://tiktokenizer.vercel.app/.

**Comment by saschaschramm** [comment]
> > It's unclear why the model returns 11 prompt tokens instead of 12. Maybe there is no \n after the role user.
> 
> See https://tiktokenizer.vercel.app/.

Thank you for sharing the link. I will update the information as soon as any official documentation becomes available. Currently, the OpenAI documentation lacks clarity regarding the special tokens used.
