### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by LolekLiam** [saschaschramm/chatgpt#3]
i am not a plus member, yet i see in my url bar `https://chat.openai.com/?model=text-davinci-002-render-sha`. the model is not for plus users only now as far as i know.

**Comment by saschaschramm** [comment]
> i am not a plus member, yet i see in my url bar `https://chat.openai.com/?model=text-davinci-002-render-sha`. the model is not for plus users only now as far as i know.

Thanks for the info. The original description of the model was sourced from OpenAI. However, it has since become outdated. I will update the README
