### ISSUE TITLE
Question about TURBO/GPT4 on HumanEval

### ISSUE THREAD

**Issue by Cppowboy** [saschaschramm/chatgpt#4]
I am trying to reproduce the evaluation result of TURBO/GPT4 on HumanEval dataset. I use the same prompt.
```
Complete the following code. Use ```python to put the Python code in markdown quotes:\n{code}
```
However, I got 57 pass@1 for TURBO model on HumanEval. What is the params settings (temperature, topp, etc.) when you calling TURBO/GPT4 service? And is there any other tricks which may affect the evaluation results?

**Comment by Cppowboy** [comment]
What is the exact content of {code}? Is it "prompt" in the https://huggingface.co/datasets/openai_humaneval/viewer/openai_humaneval/test?row=0 dataset?


"from typing import List def has_close_elements(numbers: List[float], threshold: float) -> bool: """ Check if in given list of numbers, are any two numbers closer to each other than given threshold. >>> has_close_elements([1.0, 2.0, 3.0], 0.5) False >>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3) True """ "

**Comment by saschaschramm** [comment]
> What is the exact content of {code}? Is it "prompt" in the https://huggingface.co/datasets/openai_humaneval/viewer/openai_humaneval/test?row=0 dataset?
> 
> "from typing import List def has_close_elements(numbers: List[float], threshold: float) -> bool: """ Check if in given list of numbers, are any two numbers closer to each other than given threshold. >>> has_close_elements([1.0, 2.0, 3.0], 0.5) False >>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3) True """ "

Yes, it's the prompt:

`Complete the following code. Use ```python to put the completed Python code in markdown quotes:
from typing import List


def has_close_elements(numbers: List[float], threshold: float) -> bool:
    """ Check if in given list of numbers, are any two numbers closer to each other than
    given threshold.
    >>> has_close_elements([1.0, 2.0, 3.0], 0.5)
    False
    >>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3)
    True
    """`

**Comment by saschaschramm** [comment]
> I am trying to reproduce the evaluation result of TURBO/GPT4 on HumanEval dataset. I use the same prompt.
> 
> ```
> Complete the following code. Use ```python to put the Python code in markdown quotes:\n{code}
> ```
> 
> However, I got 57 pass@1 for TURBO model on HumanEval. What is the params settings (temperature, topp, etc.) when you calling TURBO/GPT4 service? And is there any other tricks which may affect the evaluation results?

temperature=0.0 
stop=["\ndef ","\nclass ","\nif ","\n\n#"]
top_p=default (should be 1)

I remove the markdown quotes from the completion
